### ISSUE TITLE
Newest release of KERAS does not support LeakyRELU

### ISSUE THREAD

**Issue by roestigraben** [intact-project/ild-cnn#1]
I use Keras v0.3.3 and the parameter

`activation=LeakyReLU()`

inside the model.add(Convolution2D()) method 

does not work anymore compared to v0.3.2

see bug report on  [URL](https://github.com/fchollet/keras/issues/2272)

**Comment by ghost** [comment]
@roestigraben you can remove the optional argument `activation=LeakyReLU()` from the `Convolution2D()` layer and add an extra layer with the activations just after each convolutional layer:

`model.add(Convolution2D())`
`model.add(LeakyReLU())` 

please refer to [fchollet/keras/#2272](https://github.com/fchollet/keras/issues/2272) for more details

**Comment by roestigraben** [comment]
Thanks for the hint. Very appreciated!!
